### ISSUE TITLE
Add one more in this project multiple questions at a time

### ISSUE THREAD

**Issue by Siv1439** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#10]
Add questions via PDF file and ans add via EXCEL file

**Comment by narender-rk10** [comment]
This MCQ questions adding feature via CSV file is already there you can check it!
Adding via pdf is not feasible! Then, there will be errors!

**Comment by Siv1439** [comment]
It's possible. I can see one online exam website, in this upload through pdf file at a time multiple questions and it displays student exam time it shows one by one question

**Comment by Siv1439** [comment]
Same project do u write in MVC CORE

**Comment by Siv1439** [comment]
Is there Admin, teacher and student thire logins and there restrictions is there. Or only two logins admin ,student

**Comment by narender-rk10** [comment]
> It's possible. I can see one online exam website, in this upload through pdf file at a time multiple questions and it displays student exam time it shows one by one question

Can you share the link of that website?
Practically that is possible , but there will be errors.

**Comment by narender-rk10** [comment]
> Is there Admin, teacher and student thire logins and there restrictions is there. Or only two logins admin ,student

There are only 2 types of user login: a) teacher and b) student. One user can login in only in one system.

**Comment by narender-rk10** [comment]
> Same project do u have in MVC CORE

No, you can convert this logic in MVC

**Comment by Siv1439** [comment]
ok tnx for reply

**Comment by Siv1439** [comment]
sorry bro, i need help how to run this project detail expline plz bro.. once download  code and open my pycharam application not work.. how can i insert DB file into my sql server and connect to this project , and is thire any install aditional plugin like pip install like this and run with full expline step by step plz bro...... iam waiting for u r reply ...
