### ISSUE TITLE
Your browser does not support media device

### ISSUE THREAD

**Issue by ghost** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#12]
![IMG-20211017-WA0005](https://user-images.githubusercontent.com/55235865/137624491-765c4ef1-319c-41bd-95e1-3c4cd604d8ea.jpeg)
Camera error

**Comment by narender-rk10** [comment]
You need to give permission of camera from browser
Simple!

**Comment by rohit200596** [comment]
I also permission sir
