### ISSUE TITLE
showing this error : "list Index Out of range" please help us ,awaiting for your reply

### ISSUE THREAD

**Issue by Shakti2403** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#20]
![image](https://user-images.githubusercontent.com/91454577/145680571-760edc78-3372-45ed-a4c2-9487052d9087.png)

**Comment by narender-rk10** [comment]
which version of tensorflow u are using?
use tensorflow==2.2

**Comment by Shakti2403** [comment]
Thank you so much for your reply .
