### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by github030897** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#21]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by narender-rk10** [comment]
This is not a issue, you need to debug the application, check the configuration of the app.

**Comment by github030897** [comment]
Key error :temp OTP

**Comment by github030897** [comment]
> This is not a issue, you need to debug the application, check the configuration of the app.

**Comment by github030897** [comment]
> > This is not a issue, you need to debug the application, check the configuration of the app.
> 
> 

-![Screenshot 2021-12-19 112854.png](https://user-images.githubusercontent.com/96185118/146665715-b6382ae4-75b1-4328-896c-0ab126cd6fa5.png)
I'm trying hard but it doesn't work

**Comment by github030897** [comment]
Please sir help

**Comment by github030897** [comment]
I'm trying hard but it doesn't work please solution sir
