### ISSUE TITLE
tensorflow installation error 

### ISSUE THREAD

**Issue by niharikanaidu** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#23]
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0)
ERROR: No matching distribution found for tensorflow==2.2

I'm getting this error when I try to install dependencies.It would be helpful if you suggest me any solution.
Thank you sir!

**Comment by narender-rk10** [comment]
use tensorflow==2.2 in your python dependencies
make sure that you use python 3.6 version
