### ISSUE TITLE
Tensorflow Invalid Argument Error

### ISSUE THREAD

**Issue by viharika01** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#26]
hello sir, i got stucked here 
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Unsuccessful TensorSliceReader constructor: Failed to get matching files on models/pose_model\variables\variables: Not found: FindFirstFile failed for: models/pose_model/variables : The system cannot find the path specified.
; No such process
         [[node save/RestoreV2 (defined at C:\Users\lenovo\padma\padma\face_landmarks.py:7) ]] [Op:__inference_pruned_14233]
please help me!

**Comment by narender-rk10** [comment]
Use tensorflow 2.2
