### ISSUE TITLE
res10_300x300_ssd_iter_140000.caffemodel file is missing??

### ISSUE THREAD

**Issue by michaelbahik** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#27]
![Capture](https://user-images.githubusercontent.com/47878357/151728707-12734ca5-5d46-4ae8-9e40-55b17977d704.JPG)

**Comment by drac-0011** [comment]
Download and place the file inside /models

https://github.com/gopinath-balu/computer_vision/raw/master/CAFFE_DNN/res10_300x300_ssd_iter_140000.caffemodel
