### ISSUE TITLE
Requirements. txt

### ISSUE THREAD

**Issue by dydean** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#30]
It saying
Could not find a version that satisfy flask_WTF==0.14.3(FROM VERSIONS :NONE)!

**Comment by dydean** [comment]
Yes I'm facing the same issue

**Comment by narender-rk10** [comment]
https://stackoverflow.com/questions/55662888/no-module-named-flask-wtf-after-trying-to-install-flask-wtf-with-pip-install
Ref this

**Comment by narender-rk10** [comment]
That lib is deprecated.
