### ISSUE TITLE
Database file missed. any help?

### ISSUE THREAD

**Issue by alagu229** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#5]
Importing and requirements downloaded then fixed the errors also but without db we cant even run the register section also.
so if possible pls help me with this?

**Comment by narender-rk10** [comment]
DB ADDED 

YOU WANT TO USE FOR GOVT?

https://github.com/narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM/tree/main/DB
