### ISSUE TITLE
Db 

### ISSUE THREAD

**Issue by Rutuja2727** [narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM#7]
Database is Missing can anyone help me out
#

**Comment by narender-rk10** [comment]
DB ADDED CHECK IT

https://github.com/narender-rk10/MyProctor.ai-AI-BASED-SMART-ONLINE-EXAMINATION-PROCTORING-SYSYTEM/tree/main/DB
